## base image ubuntu 
FROM ubuntu 
# RUN is used to execute a command during the build process of the image
RUN apt-get update
# CMD Specifies what will be executed when the container starts
CMD ["echo", "Hello my name is Akash"]