version: "3"
services:
  prom-server:
    image: prom/prometheus:latest
    container_name: prom-server
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
