apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: app1
  name: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: app1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: app1
    spec:
      containers:
        - image: akashvarunp/myportfoliokube:latest 
          name: app1test1
          ports:
            - containerPort: 5173
              protocol: TCP
      restartPolicy: Always
