apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: app2
  name: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: app2
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: app2
    spec:
      containers:
        - image: akashvarunp/portfolioserver-kube:latest
          name: app2
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
